### ISSUE TITLE
Task list for 8th Nov to 13th Nov >>  14th to 21th Nov

### ISSUE THREAD

**Issue by udkumar** [Bridgeconn/vachan-api#27]
- [x] Deploy feature branch to staging
- [x] Production server ready API as well ad UI
- [x] DB backup
- [x] Feature branch delete after merge
- [ ] Auto deploy with circle ci - 1*
- [x] Update Wikki for the process of feature branch test and deploy
- [x] Configured usfm and graphdb on DO
- [x]  Mapped DNS fro usfm and graph from GoDaddy's side
- [x] Swagger setup on staging server
- [ ] check DO backup possibility
- [ ] Function testing suggested on slack - 2*- circle ci
