### ISSUE TITLE
Implement hard delete

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#405]
Now we  have the feature of "soft delete" for all the contents in our DB. We are not providing users ability to delete something from Db, but only allowing them to de-activate the contents by setting the status flag to False.

Based on this article, [Soft Deletion Probably Isn't Worth It](https://brandur.org/soft-deletion), we could consider implementing a hard delete on our DB and keeping a **deleted_items_table** to be able to keep track of older contents and be able to manually recover things if required.

Another disadvantage we have in our current system of using soft delete, which was not mentioned in the article is this:

Suppose we have an item created by a user, which was wrong and was deactivated. Later if another entry needs to be made, with same value for a field with unique constraint(say name), then we only have the option of re-activating(editing) the older entry. This might become a problem in a scenario where access rights on the item clashes with our interests. For example, if a project was created by the name "Hindi_BCS_translation" and was de-activated. Suppose we later have a project which needs to be named the same, and the user handling the new project is a different person, he/she will not have edit rights on the first created-and-deactivated project. That name kind of gets taken permanently. This kind of problem can arise with all types of contents like projects, token-translations, dictionary entries, Bible and other contents etc etc.

**Comment by kavitharaju** [comment]
Tasks breakdown
- [x] DELETE v2/contents
- [x]  DELETE v2/languages
- [x] DELETE v2/licenses
- [x] DELETE v2/versions
- [x] DELETE v2/sources
- [x] DELETE v2/commentaries/{source}
- [x] DELETE v2/dictionaries/{source}
- [x] DELETE v2/infographics/{source}
- [x] DELETE v2/biblevideos/{source}
- [x] DELETE v2/bibles/{source}/books
- [x] DELETE v2/bibles/{source}/audios
- [x] DELETE v2/autographa/projects
- [x] DELETE v2/autographa/project/user 
- [x] DELETE v2/autographa/project/sentences
- [x] DELETE v2/nlp/gloss
- [x] DELETE v2/lookup/stopwords/{lang}
- [x] PUT v2/restore
- [ ] DELETE v2/deleted-items

**Comment by shimilgithub** [comment]
> Tasks breakdown
> 
> * [x]  DELETE v2/contents       
> * [x]   DELETE v2/languages
> * [x]  DELETE v2/licenses
> * [x]  DELETE v2/versions
> * [ ]  DELETE v2/sources
> * [ ]  DELETE v2/commentaries/{source}
> * [ ]  DELETE v2/dictionaries/{source}
> * [ ]  DELETE v2/infographics/{source}
> * [ ]  DELETE v2/biblevideos/{source}
> * [ ]  DELETE v2/bibles/{source}/books   #498 
> * [ ]  DELETE v2/bibles/{source}/audios
> * [ ]  DELETE v2/autographa/projects
> * [ ]  DELETE v2/autographa/project/sentences
> * [ ]  DELETE v2/nlp/gloss
> * [ ]  DELETE v2/lookup/stopwords/{lang}
> * [ ]  PUT v2/restore
> * [ ]  DELETE v2/deleted-items
